version: '2'
services:
    web:
        build:
            context: ./env/nginx
        volumes:
            - ./app:/var/www/app
        ports:
            - "8000:80"
        links:
            - app
    app:
        build:
            context: ./env/php
        volumes:
            - ./app:/var/www/app